In [49]:
import pandas as pd
import numpy as np

df = pd.read_csv('ecommerce_dataset.csv', names = ['category','discription'], header = None)
print(df.shape)
df.head()

(50425, 2)

    category                                        discription
0  Household  Paper Plane Design Framed Wall Hanging Motivat...
1  Household  SAF 'Floral' Framed Painting (Wood, 30 inch x ...
2  Household  SAF 'UV Textured Modern Art Print Framed' Pain...
3  Household  SAF Flower Print Framed Painting (Synthetic, 1...
4  Household  Incredible Gifts India Wooden Happy Birthday U...

In [50]:
df.dropna(inplace=True)
df.shape

(50424, 2)

In [51]:
df.category.value_counts()

category
Household                 19313
Books                     11820
Electronics               10621
Clothing & Accessories     8670
Name: count, dtype: int64

In [52]:
df.category.replace("Clothing & Accessories", "Clothing_Accessories", inplace= True)

C:\Users\ashnk\AppData\Local\Temp\ipykernel_1776\2561582744.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.category.replace("Clothing & Accessories", "Clothing_Accessories", inplace= True)

In [53]:
df.category.unique()

array(['Household', 'Books', 'Clothing_Accessories', 'Electronics'],
      dtype=object)

In [54]:
df.category = '__label__' + df.category
df.head()

             category                                        discription
0  __label__Household  Paper Plane Design Framed Wall Hanging Motivat...
1  __label__Household  SAF 'Floral' Framed Painting (Wood, 30 inch x ...
2  __label__Household  SAF 'UV Textured Modern Art Print Framed' Pain...
3  __label__Household  SAF Flower Print Framed Painting (Synthetic, 1...
4  __label__Household  Incredible Gifts India Wooden Happy Birthday U...

In [55]:
df['category_description'] = df.category + " " + df.discription
df.head()

,category,discription,category_description
0,__label__Household,Paper Plane Design Framed Wall Hanging Motivat...,__label__Household Paper Plane Design Framed W...
1,__label__Household,"SAF 'Floral' Framed Painting (Wood, 30 inch x ...",__label__Household SAF 'Floral' Framed Paintin...
2,__label__Household,SAF 'UV Textured Modern Art Print Framed' Pain...,__label__Household SAF 'UV Textured Modern Art...
3,__label__Household,"SAF Flower Print Framed Painting (Synthetic, 1...",__label__Household SAF Flower Print Framed Pai...
4,__label__Household,Incredible Gifts India Wooden Happy Birthday U...,__label__Household Incredible Gifts India Wood...

In [56]:
import re
text = "  VIKI's | Bookcase/Bookshelf (3-Shelf/Shelve, White) | ? . hi"
text = re.sub(r'[^\w\s\']', ' ', text)
text = re.sub(' +', ' ',text)
text.strip().lower()

"viki's bookcase bookshelf 3 shelf shelve white hi"

In [57]:
def preprocess(text):
    text = re.sub(r'[^\w\s\']', ' ', text)
    text = re.sub(' +', ' ', text)
    return text.strip().lower()

In [58]:
df['category_description'] = df.category_description.map(preprocess)
df.head()

,category,discription,category_description
0,__label__Household,Paper Plane Design Framed Wall Hanging Motivat...,__label__household paper plane design framed w...
1,__label__Household,"SAF 'Floral' Framed Painting (Wood, 30 inch x ...",__label__household saf 'floral' framed paintin...
2,__label__Household,SAF 'UV Textured Modern Art Print Framed' Pain...,__label__household saf 'uv textured modern art...
3,__label__Household,"SAF Flower Print Framed Painting (Synthetic, 1...",__label__household saf flower print framed pai...
4,__label__Household,Incredible Gifts India Wooden Happy Birthday U...,__label__household incredible gifts india wood...

In [59]:
df.category_description[0]

'__label__household paper plane design framed wall hanging motivational office decor art prints 8 7 x 8 7 inch set of 4 painting made up in synthetic frame with uv textured print which gives multi effects and attracts towards it this is an special series of paintings which makes your wall very beautiful and gives a royal touch this painting is ready to hang you would be proud to possess this unique painting that is a niche apart we use only the most modern and efficient printing technology on our prints with only the and inks and precision epson roland and hp printers this innovative hd printing technique results in durable and spectacular looking prints of the highest that last a lifetime we print solely with top notch 100 inks to achieve brilliant and true colours due to their high level of uv resistance our prints retain their beautiful colours for many years add colour and style to your living space with this digitally printed painting some are for pleasure and some for eternal bliss so bring home this elegant print that is lushed with rich colors that makes it nothing but sheer elegance to be to your friends and family it would be treasured forever by whoever your lucky recipient is liven up your place with these intriguing paintings that are high definition hd graphic digital prints for home office or any room'

In [60]:
from sklearn.model_selection import train_test_split
train , test = train_test_split(df,test_size=0.2)

In [61]:
train.shape , test.shape

((40339, 3), (10085, 3))

In [62]:
train.to_csv('ecommerce.train', columns=['category_description'], index= False, header=False)
test.to_csv('ecommerce.test', columns=['category_description'], index= False, header=False)

In [63]:
import fasttext
model = fasttext.train_supervised('ecommerce.train')
model.test('ecommerce.test')

(10083, 0.9690568283249033, 0.9690568283249033)

In [71]:
model.get_nearest_neighbors('table')

[(0.9949667453765869, 'air'),
 (0.9897602200508118, 'design'),
 (0.9881669878959656, 'solimo'),
 (0.9877932667732239, 'included'),
 (0.9848711490631104, '200'),
 (0.9832197427749634, 'stage'),
 (0.9831197261810303, 'applications'),
 (0.9830188751220703, 'ribbon'),
 (0.9775586724281311, 'coated'),
 (0.9769388437271118, 'softer')]

In [78]:
model.predict("ockey men's cotton t shirt fabric details 80 cotton 20 polyester super combed cotton rich fabric")

(('__label__clothing_accessories',), array([1.00001001]))

In [79]:
model.predict("wings of fire")

(('__label__books',), array([0.99804646]))